[package]
name = "grouse"
description = "A simple asset bundler for Rust."
version = "0.1.0"
edition = "2024"
authors = [ "Callum Hopkins" ]
license = "MIT"
repository = "https://github.com/callum-hopkins-dev/grouse"
readme = "README.md"
documentation = "https://docs.rs/grouse"
keywords = [ "web", "proc-macro", "hash", "file", "assets" ]
categories = [ "web-programming", "filesystem" ]

[dependencies]
grouse-macros = { version = "0.1.0", path = "../grouse-macros" }
