[package]
name = "grouse-macros"
description = "A simple asset bundler for Rust."
version = "0.2.0"
edition = "2024"
authors = [ "Callum Hopkins" ]
license = "MIT"
repository = "https://github.com/callum-hopkins-dev/grouse"
readme = "README.md"
documentation = "https://docs.rs/grouse"
keywords = [ "web", "proc-macro", "hash", "file", "assets" ]
categories = [ "web-programming", "filesystem" ]

[lib]
proc-macro = true

[dependencies]
mime_guess = "2.0.5"
proc-macro-crate = "3.3.0"
proc-macro2 = "1.0.95"
quote = "1.0.40"
sha2 = { version = "0.10.9", features = ["asm"] }
syn = "2.0.104"
walkdir = "2.5.0"
